Feature/exercicio 05
LucasAlexander13/helpper-sprint-2 pull request #2
Opened 2021-11-07 01:15 UTC by LucasAlexander13

Pronto para revisão

2021-11-07 01:16 UTC, LucasAlexander13 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Sprint 2 - Exercício 5](https://trello.com/c/W6PMK9UT/230-sprint-2-exerc%C3%ADcio-5)

2021-11-08 21:05 UTC, alanrocha-helpper requested changes

2021-11-08 21:05 UTC, alanrocha-helpper commented on Exercicio-05/script.ts
> +    vogais: RegExp = /[aáàãâäeéèêëiíìîïoóòõôöuúùûü]/gi
Utilizar nome de variaveis com camelCase -> `umaVariavel`, `outraVariavel`

2021-11-10 22:33 UTC, alanrocha-helpper commented on Exercicio-05/index.html
> +    <button class="button" type="button" onclick="numVogais()">Converter</button>
Melhoria:
Seria contar, não converter hahaha

2021-11-10 22:34 UTC, alanrocha-helpper approved these changes

2021-11-10 22:48 UTC, merged