Feature/exercicio 06
LucasAlexander13/helpper-sprint-2 pull request #3
Opened 2021-11-07 02:03 UTC by LucasAlexander13

Código do exercício 6 pronto para revisão

2021-11-07 02:04 UTC, LucasAlexander13 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Sprint 2 - Exercício 6](https://trello.com/c/j9n0g8FR/241-sprint-2-exerc%C3%ADcio-6)

2021-11-08 22:26 UTC, alanrocha-helpper requested changes

2021-11-08 22:26 UTC, alanrocha-helpper commented on Exercicio-06/funcional.ts
> +    lista_cientistas: Pessoa[];
usar camelCase para nome de variavéis. Aplicar por todo o arquivo

2021-11-08 22:26 UTC, alanrocha-helpper commented on Exercicio-06/funcional.ts
> +        return this.lista_cientistas.find((pessoa: Pessoa) => pessoa[tipo] === id)?[tipo];
Isso aqui funciona?  `pessoa[tipo] === id` ?? Isso funcionaria pode exemplo, se receber `'id'` no tipo, que no caso você passaria um `id = 1` e receberia como retorno o numero 1 também. se passar `tipo = 'bio'` não vai encontrar, mesmo o id sendo 1

2021-11-08 22:26 UTC, alanrocha-helpper commented on Exercicio-06/imperativo.ts
> +    lista_cientistas: Pessoa[];
usar camelCase para nome de variavéis. Aplicar por todo o arquivo

2021-11-10 18:22 UTC, LucasAlexander13 commented
Realizei todas as mudanças e correções solicitadas

2021-11-10 22:36 UTC, alanrocha-helpper commented on Exercicio-06/funcional.ts
> +/*----------------------------------------------------------------------------------
Comentário fora do padrão. checar no chat do Squad Sigma, contém link para a documentação do TSDoc, e um exemplo de como deve ser o comentário

2021-11-10 22:39 UTC, alanrocha-helpper commented on Exercicio-06/funcional.ts
> +    listaCientistas: Pessoa[];
transformar em privado. É um atributo que é utilizado somente dentro da classe.

2021-11-10 22:40 UTC, alanrocha-helpper commented on Exercicio-06/funcional.ts
> +class Cientistas {
Adicionar documentação conforme padrão TSDoc

2021-11-10 22:40 UTC, alanrocha-helpper commented on Exercicio-06/funcional.ts
> +    // encontra a informação da lista a partir do id passado como parâmetro
Adicionar comentário de documentação conforme TSDoc

2021-11-10 22:40 UTC, alanrocha-helpper commented on Exercicio-06/funcional.ts
> +    apagarItem(id: number): Pessoa[] {
Adicionar comentário de documentação conforme TSDoc

2021-11-10 22:40 UTC, alanrocha-helpper commented on Exercicio-06/funcional.ts
> +    alterarInfo(id: number, tipo: string, info: string): Pessoa[] {
Adicionar comentário de documentação conforme TSDoc

2021-11-10 22:42 UTC, alanrocha-helpper commented on Exercicio-06/imperativo.ts
> +class Cientistas {
Adicionar comentário de documentação conforme TSDoc

2021-11-10 22:42 UTC, alanrocha-helpper commented on Exercicio-06/imperativo.ts
> +    retornarInfo(id: number, tipo: string): string {
Adicionar comentário de documentação conforme TSDoc

2021-11-10 22:42 UTC, alanrocha-helpper commented on Exercicio-06/imperativo.ts
> +    apagarItem(id: number): Pessoa[] {
Adicionar comentário de documentação conforme TSDoc

2021-11-10 22:42 UTC, alanrocha-helpper commented on Exercicio-06/imperativo.ts
> +    alterarInfo(id: number, tipo: string, info: string): Pessoa[] {
Adicionar comentário de documentação conforme TSDoc

2021-11-10 22:44 UTC, alanrocha-helpper requested changes
em ambos os casos, adicionar uma forma para que testem o código. Um arquivo index.html que link para o script gerado a partir de caada um dos paradigmas.

2021-11-10 23:06 UTC, alanrocha-helpper requested changes
Adicionar também um meio para que realizem os testes das funções

2021-11-10 23:52 UTC, LucasAlexander13 commented
Vou organizar a pasta para criar os arquivos html. Alguma sugestão de como adicionar um meio para testarem os métodos?

2021-11-11 11:26 UTC, alanrocha-helpper approved these changes

2021-11-11 11:37 UTC, pedro-monteiro-helpper approved these changes

2021-11-11 17:48 UTC, merged